foreach(data "" "1 2 1e" "1 2 nan" "1 2 3junk")
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/invalid.txt" "${data}")
  execute_process(COMMAND "${CLI}" "${CMAKE_CURRENT_BINARY_DIR}/invalid.txt" "${CMAKE_CURRENT_BINARY_DIR}/invalid.txt" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
  if(result EQUAL 0)
    message(FATAL_ERROR "CLI accepted invalid input: ${data}")
  endif()
endforeach()
execute_process(COMMAND "${CLI}" "${CMAKE_CURRENT_BINARY_DIR}/nonexistent-input.txt" "${CMAKE_CURRENT_BINARY_DIR}/nonexistent-input.txt" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0)
  message(FATAL_ERROR "CLI accepted missing files")
endif()
